# -*- coding: utf-8 -*-
"""day 036 of 100

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xzc4TezECFLvbljigej8bwYsbpQJbY1z
"""

STOCK_NAME = "TSLA"
COMPANY_NAME = "Tesla Inc"

STOCK_ENDPOINT = "https://www.alphavantage.co/query"
NEWS_ENDPOINT = "https://newsapi.org/v2/everything"
API_KEY_S = 'S5O715D198V5BREY'
API_KEY_N = 'ee9edfeb927442d188d8f7d26ae9b936'

import requests

    ## STEP 1: Use https://www.alphavantage.co/documentation/#daily
# When stock price increase/decreases by 5% between yesterday and the day before yesterday then print("Get News").

parametes = {
    'function': 'TIME_SERIES_DAILY',
    'symbol': STOCK_NAME,
    'apikey': API_KEY_S,
}

response = requests.get(STOCK_ENDPOINT, params= parametes)
response.raise_for_status()
stock_data = response.json()

#TODO 1. - Get yesterday's closing stock price. Hint: You can perform list comprehensions on Python dictionaries. e.g. [new_value for (key, value) in dictionary.items()]

yesterday_close = float(stock_data["Time Series (Daily)"]["2025-09-04"]["4. close"])

#TODO 2. - Get the day before yesterday's closing stock price

before_yesterday_close = float(stock_data["Time Series (Daily)"]["2025-09-03"]["4. close"])

#TODO 3. - Find the positive difference between 1 and 2. e.g. 40 - 20 = -20, but the positive difference is 20. Hint: https://www.w3schools.com/python/ref_func_abs.asp

pos_diff = abs(yesterday_close - before_yesterday_close)

#TODO 4. - Work out the percentage difference in price between closing price yesterday and closing price the day before yesterday.

percentage = round(pos_diff * 100 / yesterday_close, 2)

#TODO 5. - If TODO4 percentage is greater than 5 then print("Get News").

parameters_n = {
    'apiKey': API_KEY_N,
    'q': COMPANY_NAME
}


response2 = requests.get(NEWS_ENDPOINT, params= parameters_n)
response2.raise_for_status()
news = response2.json()

    ## STEP 2: https://newsapi.org/
    # Instead of printing ("Get News"), actually get the first 3 news pieces for the COMPANY_NAME.

#TODO 6. - Instead of printing ("Get News"), use the News API to get articles related to the COMPANY_NAME.

#TODO 7. - Use Python slice operator to create a list that contains the first 3 articles. Hint: https://stackoverflow.com/questions/509211/understanding-slice-notation

top_news = news["articles"][0:3]

    ## STEP 3: Use twilio.com/docs/sms/quickstart/python
    #to send a separate message with each article's title and description to your phone number.

#TODO 8. - Create a new list of the first 3 article's headline and description using list comprehension.

news_list = [item['title'] for item in top_news]

#TODO 9. - Send each article as a separate message via Twilio.

num = 0
for headline in news_list:
  num += 1
  print(f"{num}. {headline}")



#Optional TODO: Format the message like this:
"""
TSLA: 🔺2%
Headline: Were Hedge Funds Right About Piling Into Tesla Inc. (TSLA)?.
Brief: We at Insider Monkey have gone over 821 13F filings that hedge funds and prominent investors are required to file by the SEC The 13F filings show the funds' and investors' portfolio positions as of March 31st, near the height of the coronavirus market crash.
or
"TSLA: 🔻5%
Headline: Were Hedge Funds Right About Piling Into Tesla Inc. (TSLA)?.
Brief: We at Insider Monkey have gone over 821 13F filings that hedge funds and prominent investors are required to file by the SEC The 13F filings show the funds' and investors' portfolio positions as of March 31st, near the height of the coronavirus market crash.
"""